### ISSUE TITLE
SEO metadata management

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#101]
- [x] The nuxt library must be updated to have in the below setting section an icon to do the settings of the page
- An icon should be added , use this one https://www.flaticon.com/free-icon/settings_3524659
- When clicking on this icon we should have
  - A sentence to inform the user he needs to save the page to save the informations:
   - "To save the metadata and the page url, you need to save your page" ( Pour sauver les metadatas et l'url de la page vous devez sauver la page" 
  - The metadata fields (Labels : Title,SEO description), those fields are string, for description it should be long string, In french the labels are  "Titre" and "Description SEO"
  - The URL of the page that must be editable : label : Page URL ( In french Label : URL de la page )
  - The library when updating the page will need to redirect the user to the new URL when the page is saved to let the user on the same page as the old url will no more be valid ( In the Backend to get the page it will be the URL that will be used now)
- Option to delete the page near the save page one
     - When clicking on this option there will be a big warning in red, to inform the user of what he is on the point to do
     - Title of the popup is " Delete page" ( "Supprimer la page")
     - Sentence : " Are you sure you want to delete this page ?" ("Êtes vous sur de vouloir supprimer cette page ?")
     - Buttons : Delete page that should be in red ( Supprimer la page in french), Cancel ( Annuler)
     - If you delete the page, the page is deleted successfully with a success message coming from backend
     - If you cancel popup is closed

<img width="722" alt="Screenshot 2023-05-15 at 17 53 11" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/704a32a4-b3af-41ff-9bb4-3a06da43ca2f">

Payload with metadata and url:

````

PUT /api/v1/project/63fc7b45a8823c0007d25a59/page/pageregion HTTP/1.1
Host: api.sections.geeks.solutions
origin: https://notifications.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAYYS5zYXJraXMrZW5zYW5AZXdlZXYuY29tbQAAABFwcm9qZWN0X2xvZ2dlZF9pbm0AAAAYNWZhOTMzZDBlOGRiMTkwMDAxNzFmNjc2bQAAAAp0b2tlbl90eXBlbQAAAAZub3JtYWxtAAAAB3VzZXJfaWRtAAAAGDYzZmM3YjQ2ODRhYzA1MDAwODBiZjlhY24GAJkfJTCIAWIAAVGA.alrh8DNlvs161OG-r8a2el6pBcwH_X7nsgzT_qOVm_E
Content-Type: application/json
Content-Length: 1013

{
    "page": "pageregion",
    "url": "https://testsectionregion1",
    "metadata": {
        "title": "region 1 title",
        "description": "region 1 SEO description"
    },
    "variations": [
        "1"
    ],
    "sections": [
        {
            "id": "6465c807b922eb00079d24e9",
            "weight": 1,
            "region": "region1",
            "name": "sectionregion1",
            "type": "static",
            "data": "this is a test",
            "options": 
                {
                   "title":"test",
                   "description":"test description"

                }
            
        },
        {
            "id": "6465c80ab922eb00074ffcb9",
            "weight": 1,
            "name": "sectionregion2",
            "region": "region2",
            "type": "static",
            "data": "this is a test"
        },
        {
            "weight": 1,
            "name": "sectionregionlocal",
            "region": "region2",
            "type": "local"
        }
    ]
}

````

Delete endpoint

````
DELETE /api/v1/project/60d1e1e61aa3df0006b08e07/page/6466133d223160f5dd488e64 HTTP/1.1
Host: api.sections-saas.k8s-dev.geeks.solutions
origin: https://sections-saas.k8s-dev.geeks.solutions
token: SFMyNTY.g2gDdAAAAARtAAAADGxvZ2luX2ZpZWxkc3QAAAABbQAAAAVlbWFpbG0AAAAYYS5zYXJraXMrZXdlZXZAZXdlZXYuY29tbQAAABFwcm9qZWN0X2xvZ2dlZF9pbm0AAAAYNWZjNTBmNzExNjVmMzkwMDAxZmQ0ODc4bQAAAAp0b2tlbl90eXBlbQAAAAZub3JtYWxtAAAAB3VzZXJfaWRtAAAAGDYwZDFlMWU3Y2M4NjJlMDAwNjY0YWIzNG4GAJt3VzOIAWIAAVGA.r-Cmtq15Ij19Pid7RBe051bqLAaOTd_smRK70lqakA0
````

**Acceptance testing**

- [x] Icon is added the settings section and should be the one provided
- [x] Clicking on the icon open metadata ( title and description)  and the url 
- [x] Metadata and URL can be edited
- [x] Metadata and url are saved only when saving the page
- [x] Clicking on the delete option a warning should how to prevent the user and when i confim, the page is deleted with a success message else if I cancel the popup is closed

**Comment by jfayad** [comment]
- the icon should look like this: https://www.flaticon.com/free-icon/settings_3524659
- The form should also contain a layout dropdown from which we can choose which layout we use for the page. Depending on the choice, the page edit layout and view page layout will be updated accordingly

**Comment by akramsarkis** [comment]
> * the icon should look like this: https://www.flaticon.com/free-icon/settings_3524659
> * The form should also contain a layout dropdown from which we can choose which layout we use for the page. Depending on the choice, the page edit layout and view page layout will be updated accordingly

@jfayad for the second point it will be done on issue #103

**Comment by akramsarkis** [comment]
All good, closing it
