### ISSUE TITLE
Meta tag for media

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#102]
- [x] For the sections with media, you need to integrate the SEO tag of the media that is entered when editing the media and saving it from the BO, in the html you are outputing for the images, note that it should be added as the alt tag of the image.

**Acceptance testing**

- [x] I should check that the SEO tag of the media is indeed integrated in the html you are outputing for the images ( i need your help to know how)

**Comment by jfayad** [comment]
it should be added as the alt tag of the image

**Comment by mahfouzhseineweev** [comment]
This has been tackled on Sections website for TitleTextMediaLinkContent and SectionsClients types that has content linking working

**Comment by akramsarkis** [comment]
All good here
