### ISSUE TITLE
Layout and region to be integrate for the library

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#103]
- [x] The nuxt library should be capable to read the layouts for a page, those layouts won't be read from a single file, it will actually scan the layouts (vuejs components in the nuxt app) that should be placed in a particular folder
- [x] The basic layout will be provided with the nuxt library directly , this is the one used now that is adding sections under each other
- [x] In the page settings when editing it , we need to add an option for the some settings of the page and one of them will be the layout selection that is a drop down list that will contain the available layouts.

<img width="1431" alt="Screenshot 2023-05-16 at 10 33 28" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/b825b167-fe2e-41ba-a367-21ad1f8f7b57">

- [x] When editing a page and I select a layout for it, i need to see the different regions of the page, regarding the layout chosen for it
- [x] For each region in the layout chosen, I should be able to add new sections , so the Add new section option will be per region , no more on the banner in the top if a layout different that the default one is used.
- [x] When the section is added to a region we should be able to do the actions we are doing actually that are, moving it, editing it, deleting it , and check the anchor of it
- [x] We need to be able move a section from a region to another
- [x] When getting the page , it  returns the name of the layout, the name of the regions in this layout and the weight of each sections in this regions, which will allow the nuxt library to read those and display the  page as it should regarding its layout and its region and the position of the sections in those regions.

As you can see below, in the page the section has a weight and a region, this is what you need to specify the region where the section is and its position in this region, here region is null because none was entered during the creation:

````
 "sections": [
        {
            "weight": 1,
            "type": "static",
            "settings": [
                {
                    "profil": {
                        "media_id": "64621da4e20df80008991bd1"
                    }
                }
            ],
            "render_data": "",
            "region": null,
            "name": "Section15may1",
            "linked_to": "",
            "id": "64621bace20df80008787d30",
            "error": null
        },
````

Here as you can see you have the layout that is the standard one ( The default one ), but when we will select another one, this is this one that will show when getting the page.

````
    ],
    "page": "homepagetest15may",
    "layout": "standard",
    "last_updated": 1684152040,
    "invalid_sections": [],
    "id": "64621dd1223160f5dd356681"
}
````

- [ ] You need to make sure that this management won't broke the management that are already done:
- SEO tag
- Performance
- SSR
- etc

**Acceptance testing**

- [x] In the new settings option i should see a layout drop down list showing me the available  layout for this page that will be extracted from vuejs component layout
- [x] By default the layout of the page selected will be the basic one
- [x] If i modify the layout, the delimitation of the regions of the page should show regarding the layout choosen
- [x] For each region i should have the option to add a section to it
- [x] For each section when added, i must be able to edit it, move it, delete it , see its anchor
- [x] I must be able to move a section from a region to another
- [x] When viewing the page it should be displayed regarding the layout a choose for it and with the correct regions and sections in the correct positions in the regions
- [x] Make sure that this management won't broke the management that are already done:
- SEO tag
- Performance
- SSR
- etc

**Comment by jfayad** [comment]
- the layouts won't be read from a single file, it will actually scan the layouts (vuejs components) that should be placed in a particular folder)
- The information about layout and regions is already returned by the backend, so all the work is on the library's side now

**Comment by mahfouzhseineweev** [comment]
Link to the conversation https://mattermost.gl.eweev.com/eweev/pl/b55e1bnkbidbikwz7ha8gicq5h

**Comment by mahfouzhseineweev** [comment]
Layout component example that must be placed inside `sections/layouts` folder on the host project:

```html
<template>
  <div>
    <div>
      <slot name="top"></slot>
    </div>
    <div class="grid grid-cols-2">
      <div class="col-span-1">
        <slot name="right"></slot>
      </div>
      <div class="col-span-1">
        <slot name="left"></slot>
      </div>
    </div>
    <div>
      <slot name="bottom"></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    slotNames: {
      type: Array,
      default() {
        return ['left', 'right', 'top', 'bottom']
      },
    },
  },
}
</script>
```

**Comment by mahfouzhseineweev** [comment]
The work on this issue is done and a separate PR for layouts is sent, once Akram is back I will send an MR on Sections Website with the layouts update for QA

**Comment by akramsarkis** [comment]
I opened a QA issue for Layout https://github.com/Geeks-Solutions/vue-sections/issues/119 that include QA as well of issue 118
