### ISSUE TITLE
Multi level path for dynamic page feature and fix of the support of / for the path update

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#111]
- [ ]  Forbid a / that comes after a string... so / will work but xyz/ won't work and thus xyz/abc won't work but / will work (and so will /page too)
- [ ] Support the dynamic page at any mutli-level path

**Acceptance testing**

- [ ] Support the dynamic page at any mutli-level path
- [ ] have / supported for the path for the Home page, so if the path is updated with / it will work, or /page1 but if it is updated by page1/ or page1/page2 it won't

**Comment by jfayad** [comment]
the statement 
> but if it is updated by page1/ or page1/page2 it won't

is not correct, with this issue even xxx/yyy will work properly

**Comment by akramsarkis** [comment]
Duplicate of an issue on bo geeks app that is done now, closing it
