### ISSUE TITLE
Timebox on Library must manage language supported for all the sections of the project

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#112]
- [x] Timebox on Library must manage language supported for all the sections of the project even the one specific to the project
- Any section I add or edit, the tabs corresponding to the language supported and configured in the library should show with their form

**Acceptance testing**

- [x] Any section I add or edit, the tabs corresponding to the language supported and configured in the library should show with their form

**Comment by mahfouzhseineweev** [comment]
This is linked to issue https://github.com/Geeks-Solutions/vue-sections/issues/110 for it to be finalized after fixing the translation for all the sections where the Translation component is used
