### ISSUE TITLE
QA Library languages

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#115]
**General**

- [x] I must have the different languages in any pages when editing it, not on a specific page
- [ ] For each language let's have automatically a specific label for the title and description fields  like
- Title in English, Title in French, etc ( Titre en Anglais , ...)
- SEO description in English , ... ( Description SEO en anglais ...., )
- [x] When saving the page with sections having several languages like Testvariations, the success message is showing twice

**Settings**

- [x] When  I should have an error, the grey shadow is there  but no message is showing, here what i have in the console, when for example the path is blank:

![Screenshot 2023-06-19 at 15 18 30](https://github.com/Geeks-Solutions/vue-sections/assets/82215775/577795ec-10c5-49de-a0c7-ef60cb336203)

- [x] Following this steps, I don't have the correct translation for the English version, I need to switch to an other language then come back to the english one
- Click on the settings icon
- Fill in all the languages ( Here we have English, french, spanish and italian ) , then click on Save
- Click again on the settings icon ( Remember you saved when you were on the Italian language)
- You will see that for English this is the Italian values that are there
- If you open the settings then select a language, then close the popup and open it again. this is the values of the last language you were that are showing for english

<img width="957" alt="Screenshot 2023-06-19 at 15 23 05" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/db8afd9b-5768-4b56-bd6f-d3f1886be32a">

**New section Textbutton rowtest and wyzywig**

- [x] Each time I edit the section and submit data, I have a new section created instead of the same one edited

<img width="1434" alt="Screenshot 2023-06-19 at 15 35 28" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/4dfada6d-ef17-464e-86b4-2ac2b5e07494">

**Acceptance testing**

**General**

- [x] I must have the different languages in any pages when editing it, not on a specific page
- [ ] For each language let's have automatically a specific label for the title and description fields like 
- Title in English, Title in French, etc ( Titre en Anglais , ...)
- SEO description in English , ... ( Description SEO en anglais ...., )
- [x] When saving the page with sections having several languages like Testvariations, the success message is showing twice, ot should only show once

**Settings**

- [x] When  I should have an error, the grey shadow is there  but no message is showing, here what i have in the console, when for example the path is blank, the section should work like ti was before adding the languages:
- [x] Following this steps, I don't have the correct translation for the English version, I need to switch to an other language then come back to the english one, I should have directly the correct one for English
- [x] Same bug as above when you edit the settings, then you go to another language, you close it, then you open it again, so as well in this case it should show the correct translations value

**New section Textbutton rowtest and wyzywig**

- [x] Each time I edit the section and submit data without modifying it, I have a new section created instead of the same one edited, the existing one should be edited

**Comment by mahfouzhseineweev** [comment]
>  For each language let's have automatically a specific label for the title and description fields like
Title in English, Title in French, etc ( Titre en Anglais , ...)
SEO description in English , ... ( Description SEO en anglais ...., )


@akramsarkis We need to have the library dynamic and additional translations must come from the host project, because it is not possible to automatically generate translations for additionnal languages which is why I kept them simple like Title and Description. Currently the library supports english and french translations, but additionnal language labels must be added from the host project localization files

**Comment by akramsarkis** [comment]
@mahfouzhseineweev 

- [ ] For the label of the fields, you did not put specific label for each language
- [ ] If there is an error specific to english, it should not show in the other language like for TextbuttonRowTest, i left for english link empty then i clicked submit data and got error that it is required and when i went to french  for example, the error message is showing there as well which is wrong

**Comment by akramsarkis** [comment]
Ok I read your comments and will add the second point in the  new issue i will create for  sections website
