### ISSUE TITLE
Fixes to be done on bugs found while checking prigo felice

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#12]
When I login to section then click on the button to access the site 

1. The loading icon is showing but not long time, so there is a while where nothing is happening, till the content shows ( Note that when I access the site as a user not admin so just accessing the site as user lambda, the load is working fine.

1. To have the edit button showing I need to refresh my page, it is not showing directly

**Comment by jfayad** [comment]
@jat10 I'm assigning this issue to you as you worked on the login feature.

**Comment by jat10** [comment]
@jfayad okay i will check that

**Comment by jfayad** [comment]
@mahfouzhseineweev On top of what is described above we also noticed that when you refresh the page the Edit page button switches to Create page and then edit page again etc...

This is probably related to how the library is handling the response from the server

**Comment by akramsarkis** [comment]
This one has QA, so it cannot be closed

**Comment by akramsarkis** [comment]
All good
