### ISSUE TITLE
Layout drop down and checkbox display adjustment plus small adjustment for empty section

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#121]
- [x] Move the icons to export, import, delete and access the settings to the first line and aligned with the sentence "Your changed will be published when the page is saved"

<img width="1437" alt="Screenshot 2023-10-05 at 11 19 11" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/1aaf4a6c-4d4d-4810-9778-6b6b5f8cf23c">

- [x] Add a button to the left of the "Add a new section" button, that label is "Edit layout" ( Editer le layout )
- [x] When you click on the button to edit the layout, the layout drop down list and the highlight region option will show and the other buttons will swipe to the right
- [x] Replace Highlight regions label by Highlight ( Surligner)
- [x] Replace the highlight checkbox by a toggl that has the blue color like the buttons when it is activated else it is gray
- [x] In french the Create a new type of sections is overriding the add new section so make sure to fix it

<img width="721" alt="Screenshot 2023-10-05 at 11 24 41" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/d71d6b0e-7277-4719-91c2-5603f35cd186">

- [x] When a section is empty like empty wyzywig it is showing with {}, like the picture below, we must not see this, it should be empty

<img width="736" alt="Screenshot 2023-10-05 at 14 07 53" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/e04acea5-a3b5-4f05-b963-4b1747bfc7f0">

- [x] When I am in french the empty and not empty section like wyzywig is not showing correctly, the empty should not show anything and the filled in should only show the content, not like below:

<img width="747" alt="Screenshot 2023-10-05 at 14 11 01" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/0c4a628e-6c0f-49f6-b5dd-1f737b5ddf06">

**Acceptance testing**

- [x] Move the icons to export, import, delete and access the settings to the first line and aligned with the sentence "Your changed will be published when the page is saved"
- [x] Add a button to the left of the "Add a new section" button, that label is "Edit layout" ( Editer le layout )
- [x] When you click on the button to edit the layout, the layout drop down list and the highlight region option will show and the other buttons will swipe to the right
- [x] Replace Highlight regions label by Highlight ( Surligner)
- [x] Replace the highlight checkbox by a toggl that has the blue color like the buttons when it is activated, else it is gray
- [x] In french the Create a new type of sections is overriding the add new section so make sure to fix it
- [x] When a section is empty like empty wyzywig it is showing with {}, like the picture below, we must not see this, it should be empty
- [x] When I am in french the empty and not empty section like wyzywig is not showing correctly, the empty should not show anything and the filled in should only show the content

**Comment by mahfouzhseineweev** [comment]
@akramsarkis 

> When you click on the button to edit the layout, the layout drop down list and the highlight region option will show and the other buttons will swipe to the right

* The layout drop down and the highlight region option will be still to the of the Restore button, correct ?

* What do you mean exactly by `other buttons will swipe to the right`

* The layouts drop down and the highlight region option will be hidden by default and they will show after pressing the edit layout button. However what happens after ? I mean re-clicking in the edit layout again will make the drop down and the highlight option disappear ?

**Comment by akramsarkis** [comment]
> @akramsarkis
> 
> > When you click on the button to edit the layout, the layout drop down list and the highlight region option will show and the other buttons will swipe to the right
> 
> * The layout drop down and the highlight region option will be still to the of the Restore button, correct ?
> * What do you mean exactly by `other buttons will swipe to the right`
> * The layouts drop down and the highlight region option will be hidden by default and they will show after pressing the edit layout button. However what happens after ? I mean re-clicking in the edit layout again will make the drop down and the highlight option disappear ?

@mahfouzhseineweev 

- No it should show before the add new section
- well as the layout and toggl will show before add new section, the rest of the buttons must swipe to the right
- Good question, well once you click on it select a layout then save the page , it should be hidden. And if you don't save the page , when you click on it, it should as well hide the layout options, so after clicking on it lets have the label be "Hide layout options" " Cacher les options du layout"

**Comment by akramsarkis** [comment]
@mahfouzhseineweev , there is one more point to fix that is the Restore option, if I saved the page with layout 2 for example and then I move to standard without saving and I click on restore it should restore me the layout 2 that was saved last thing

**Comment by akramsarkis** [comment]
Hello @mahfouzhseineweev , I have one feedback, when I add an empty section, let's have the option of the section showing completely, nos they are truncated

<img width="793" alt="Screenshot 2023-10-09 at 10 27 45" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/c025e895-7a27-4758-b7fb-e8e1af36e586">

**Comment by akramsarkis** [comment]
Hello @hussein661 ,

If I add one empty it is fine , but if I add several the one before the last one are truncated as well

<img width="802" alt="Screenshot 2023-10-10 at 14 18 28" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/b9b4f7bb-3432-4650-a5bf-444e11b36498">

**Comment by mahfouzhseineweev** [comment]
Hello @akramsarkis ,

That last reported problem is completely normal, adding multiple empty sections that has zero height will result to the above and the user can safely delete the empty section by pressing on the icon that will always show after the last update. I am quite sure the user will not need empty sections in his page.

A solution for this would be to give the section view a predefined height which is not optimal given that the section should have the height of its content, let me know what you think.

**Comment by akramsarkis** [comment]
> Hello @akramsarkis ,
> 
> That last reported problem is completely normal, adding multiple empty sections that has zero height will result to the above and the user can safely delete the empty section by pressing on the icon that will always show after the last update. I am quite sure the user will not need empty sections in his page.
> 
> A solution for this would be to give the section view a predefined height which is not optimal given that the section should have the height of its content, let me know what you think.

Hello @jfayad ,

Please to check the comment above . Can we keep it as the picture below ?  Indeed this is not a regular case, it should not happen in the real life to add several empty sections, and the user can still access the options even though they are not showing totally. Please to let us know:

<img width="802" alt="273881552-b9b4f7bb-3432-4650-a5bf-444e11b36498" src="https://github.com/Geeks-Solutions/vue-sections/assets/82215775/6df9f6d4-cabf-4d03-9cca-9b18f8749b05">

**Comment by jfayad** [comment]
Indeed, this is quite an usual situation and doesn't need to be tackled urgently.

**Comment by akramsarkis** [comment]
> Indeed, this is quite an usual situation and doesn't need to be tackled urgently.

Ok, i will open then separate issue for it and close this one

**Comment by akramsarkis** [comment]
Here the issue : https://github.com/Geeks-Solutions/vue-sections/issues/122
