### ISSUE TITLE
Update the UI to be able to delete a newly created static section type

### ISSUE THREAD

**Issue by jfayad** [Geeks-Solutions/vue-sections#19]
The endpoint to perform the DELETE already exists, it's just a matter of calling it with the right section type.

I suggest we put an X icon at the top right corner of all the section types that are specific to this project, pressing the icon would run the query to delete it.

In case the query succeeds:
- We update the list of static section types so we can see the one we deleted is not here anymore

in case the query fails:
- We display the error message to provide guidance on what needs to be done

A static section type can be deleted in the following cases:
- It belongs to the current project
- no section of that type is left on this project

If you notice a wrong behavior, please file an issue to sections by sending an email to `service+eweev-geeks-sections-360-issue-AT gl.eweev.com`

**Comment by akramsarkis** [comment]
This one has a QA on the text of the message, the error is there

**Comment by akramsarkis** [comment]
All good now
