### ISSUE TITLE
Glitch when editing a page in section

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#51]
- [ ] Following this scenario, there is nothing telling the user that the page was edited previously
- User 2 has the page of the site opened from a while ( he didn't do any modification)
- User one edited the page then save
- User 2 click on the button to edit the page , then edit it and save it and consequently all the changes of user 1 has gone

We need when user 2 try to edit the page, in case the version of the page he is seeing is not the more recent one and edit happened on it, to have a message displayed to user 2 saying " The version of the page you have is an old one, please to refresh your page before doing any modification.

- [ ] can you also move the messages (alerts, warnings, errors etc...) to show at the right of the screen so they don't hide the action buttons

**Comment by mahfouzhseineweev** [comment]
@jfayad , According to Akram this will be a quick fix that I need to estimate and work on.

But is this implemented backend wise ? and how will user 2 knows that the version of the page He is trying to edit is an old one ? Shouldn't this be also groomed between front and backend to find a solution ?

**Comment by jfayad** [comment]
I think you can issue a get request to the page when you press the edit button and see if the timestamp you get is the same as the one you already loaded for that page.

No need to overcomplicate it...

**Comment by mahfouzhseineweev** [comment]
The issue took more time then expected because there was a point that has been added after the estimate is done
