### ISSUE TITLE
Create  hash to be used then in the header for the creation and edition of the whitelist

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#74]
- [x] Create  hash to be used then in the header for the creation and edition of the whitelist, this for security

**Comment by jfayad** [comment]
This should take the form of a function that gets executed on server side only.

It will read a private env. variable which will be named `{app_id}-hashkey` 

the function will also take a list of fields to concatenate together and hash. (the data string) and the app_id

`sign(app_id, data)`

The concatenation will be done client side (the section type implementation will be doing this) and the hash function will do the following:
- prepend the timestamp of the request to the data string
- load the private hashkey for the app_id
- generate an HMAC SHA256 `hash` of the data using the hashkey 
- return the signature string in the following format `timestamp=hash`

in the secure requests to issue toward the third party app API, add the `signature` header with a value equal to the return string of the `sign` function

**Comment by akramsarkis** [comment]
All good, can be closed

**Comment by jfayad** [comment]
why is this
