### ISSUE TITLE
After adding new sections there is no way to provide the 3 components

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#9]
- After adding new sections there is no way to provide the 3 components mentioned in the congrats message ( I am not sure this is done backend ), more of that when clicking agree on the congrats message you are back to the first step of adding a section.

![Screen Shot 2021-04-09 at 3 19 47 PM](https://user-images.githubusercontent.com/82215775/114179371-8c451f00-9947-11eb-8979-2ce258398a9d.png)

**Comment by jfayad** [comment]
@akramsarkis this is to be provided on the frontend vuejs project directly (in the code) this message is to indicate the components that need to be created

**Comment by akramsarkis** [comment]
@jfayad just one question, in the second part of my sentence was mentioning that that when I click on agree I am redirected to the popup to create new section, is this expected ?

**Comment by jfayad** [comment]
that could be enhanced and instead show the list of section types
