### ISSUE TITLE
Feedback on the PR comments tackled and issue 93

### ISSUE THREAD

**Issue by akramsarkis** [Geeks-Solutions/vue-sections#95]
- [x] When you create a static section then you click on done in the last step and you click to create another static section, please to have the section name and fields empty
- Click on create static section
- Fill in the section name and field
- Click to continue
- Click on done
- Check the value of the section type name

**Feedback on the tests for the PR comments tackled**

***When language is french***

- [x]  creating a static section then reaching the success message popup "static" should be written "statique"

<img width="687" alt="Screenshot 2023-05-02 at 16 57 37" src="https://user-images.githubusercontent.com/82215775/235689328-98e0e27a-cd5e-4e49-9786-51e8f3a4e59a.png">

- [x] In the first bullet "icon" should be "icône", "fenetre" should be "fenètre" and let's have the whole sentence on one line

<img width="685" alt="Screenshot 2023-05-02 at 16 58 03" src="https://user-images.githubusercontent.com/82215775/235689372-91a3ae91-02a9-42b9-8dc4-89ac5bda314d.png">

- [x] The last bullet in french should be " Un aperçu pour qu'elle puisse être affichée comme vous le voulez pour les visiteurs du site"
- [x] The buttons to export and import sections should have label "Exporter les sections", "Importer les sections"
- [x] Deconnecter should be "Déconnecter"
- [x] Submit Data in french for any sections should be "Soumettre les données"
- [x] For the section TitleTextMedia ( **This needs to be done for all the sections**) if I leave the french english version empty then i go to the french version and click on Submit Data without filling anything, i have no error message showing, we need to add one to show which fields are required in the english version without the need to go to the english version "There a required fields for the english version, please to check it to fill them", " Il ya des champs requis pour la version anglaise, veuillez s'il vous plait y accéder pour les remplir"
- [x] For any sections "Insert text here" should be " Insérer le texte ici"
- [x] For any sections "upload" should be "Télécharger"
- [x] For any sections " Translation" in french should be "Traduction"
- [x] For SectionPackages:
- Free start label in french should be "Label de démarrage pour le package Gratuit"
- Free start link in french should be " Lien de démarrage pour le package Gratuit"
- we need to add package for any label of the different packages like 
 - "Prix du package gratuit" ( Same for the other packages)
 - "Date du package gratuit"
 - "Lien du package gratuit"
 - "Fonctionalité du package gratuit"
 - "Média pour le package gratuit"
- the point above should be done in english too for all the packages
 - Free package price
 - Free package date
 - Free package link
 - Free package Features
 - Free package start label
 - Free package start link
 - Free package media
- [x] For Termspolicy section, in french the label of the wyzywig should be "Termes et Police" and in english "Terms and Policy"
- [x] More of this for termspolicy section , If I don't fill anything and I click on Submit data nothing is showing we need an error message "Required field", " Champ requis"

**Comment by akramsarkis** [comment]
@jfayad concerning the translation in french of the success/error message, there is some coming from backend, how can i make sure if they have translation in french from Postman as we are not logged in in section website so we cannot do this through a token, I am asking as I have added some points here related to messages coming from backend so I need:

- how to test from postman if there is a translation or not for french ?
- If there is not , how you need to handle this to let hussein know when to use the french one and when to use the english one

I suggest that if there is no translation available still, to not delay the deploy of the PR for this and to open a separate issue to handle those on sections backend and one to handle them here in the library

**Comment by mahfouzhseineweev** [comment]
> When a section is delete the message in french should be " La section statique a été supprimée avec succès"

This one is coming from backend as well @akramsarkis

**Comment by mahfouzhseineweev** [comment]
> For any sections "Insert text here" should be " Insérer le texte ici"

This is coming from the wysiwig and it not feasible to translate it @akramsarkis

**Comment by jfayad** [comment]
you mean it's coming from the quill editor ? Have you checked the feasibility of this before saying it ain't possible ?

**Comment by akramsarkis** [comment]
> you mean it's coming from the quill editor ? Have you checked the feasibility of this before saying it ain't possible ?

@hussein661 have you checked this before sending the MR ?

**Comment by mahfouzhseineweev** [comment]
@jfayad I did and the quill editor does not support localization

**Comment by akramsarkis** [comment]
@mahfouzhseineweev please to fix the below points

**General**

- [x] The message I requested when i am in french translation and i click on submit data without filling fields in the english one is showing now but make it that it scroll to the message without the need to scroll manually

**SectionPackages**

- [x] "Nombres de pages des package gratuites" should be "Nombre de pages du Package Gratuit"
- [x] "Fonctionalités du package gratuite (séparée par -)" should be "Fonctionalité du package Gratuit"
- [x] For corporate package, there is several labels not translated in french

<img width="538" alt="Screenshot 2023-05-03 at 11 29 19" src="https://user-images.githubusercontent.com/82215775/235867030-5b650bf0-0859-4096-86e4-4ce01edbdd6e.png">

- [x] In english you didn't add package for the below labels:

<img width="510" alt="Screenshot 2023-05-03 at 11 30 57" src="https://user-images.githubusercontent.com/82215775/235867404-572ddf06-a81c-4100-aa84-cc67e9bdf3fc.png">
